/** Shared button, action, option, and segmented-control style primitives. */

const buttonMicroInteractionClass = 'transition-[background-color,border-color,color,transform] duration-150 ease-out hover:-translate-y-px motion-reduce:transform-none motion-reduce:transition-colors [&_svg]:transition-transform [&_svg]:duration-150 [&_svg]:ease-out hover:[&_svg]:translate-x-[1px] motion-reduce:[&_svg]:transform-none';

export const compactUtilityButtonClass = `inline-flex h-11 min-h-11 min-w-[4.9rem] shrink-0 items-center justify-center rounded-2xl border border-arsm-accent/30 bg-arsm-accent-subtle/85 px-5 text-[12px] font-medium leading-tight text-arsm-primary hover:bg-arsm-accent-subtle focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/40 max-[320px]:min-w-[3.9rem] max-[320px]:px-3.5 max-[320px]:text-[11px] dark:border-arsm-accent-dark/30 dark:bg-arsm-hover-dark/80 dark:text-arsm-primary-dark dark:hover:bg-arsm-hover-dark dark:focus-visible:ring-arsm-focus-ring/30 ${buttonMicroInteractionClass}`;
export const iconButtonClass = `inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-arsm-border bg-arsm-input text-arsm-label hover:bg-arsm-toggle-bg hover:text-arsm-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/40 disabled:cursor-not-allowed disabled:opacity-60 dark:border-arsm-border-dark dark:bg-arsm-input-dark dark:text-arsm-label-dark dark:hover:bg-arsm-toggle-bg-dark dark:hover:text-arsm-primary-dark ${buttonMicroInteractionClass}`;
export const schedulerNavIconButtonClass = `inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-arsm-border bg-arsm-input text-arsm-label hover:bg-arsm-toggle-bg hover:text-arsm-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/40 disabled:cursor-not-allowed disabled:border-arsm-border/60 disabled:opacity-50 disabled:hover:bg-arsm-input disabled:hover:text-arsm-label dark:border-arsm-border-dark dark:bg-arsm-input-dark dark:text-arsm-label-dark dark:hover:bg-arsm-toggle-bg-dark dark:hover:text-arsm-primary-dark dark:disabled:border-arsm-border-dark/60 dark:disabled:hover:bg-arsm-input-dark dark:disabled:hover:text-arsm-label-dark ${buttonMicroInteractionClass}`;
export const modalConfirmCloseButtonClass = 'inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-lg border border-transparent bg-transparent text-arsm-muted transition-colors hover:bg-arsm-toggle-bg/65 hover:text-arsm-primary active:bg-arsm-toggle-bg/80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/35 disabled:cursor-not-allowed disabled:opacity-50 dark:text-arsm-muted-dark dark:hover:bg-arsm-toggle-bg-dark/70 dark:hover:text-arsm-primary-dark dark:active:bg-arsm-toggle-bg-dark/80';
export const iconDangerButtonClass = `inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-arsm-error-border bg-arsm-error-bg text-arsm-error-text hover:bg-arsm-error-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-error-hover/40 disabled:cursor-not-allowed disabled:opacity-60 dark:border-arsm-error-dark dark:bg-arsm-error-bg-dark dark:text-arsm-error-text-light dark:hover:bg-arsm-error-bg-dark/80 dark:focus-visible:ring-arsm-error-dark/40 ${buttonMicroInteractionClass}`;

export const optionTileBaseClass = 'relative inline-flex h-11 min-h-11 w-auto max-w-full shrink-0 cursor-pointer items-center gap-2 overflow-hidden rounded-lg border px-3 py-2 text-xs transition disabled:cursor-not-allowed';
export const optionTileActiveClass = 'border-arsm-accent bg-arsm-toggle-bg text-arsm-primary ring-1 ring-arsm-accent/25 dark:border-arsm-accent-dark dark:bg-arsm-toggle-bg-dark dark:text-arsm-primary-dark dark:ring-arsm-accent-dark/30';
export const optionTileInactiveClass = 'border-arsm-border bg-arsm-input text-arsm-label hover:bg-arsm-toggle-bg dark:border-arsm-border-dark dark:bg-arsm-input-dark dark:text-arsm-label-dark dark:hover:bg-arsm-toggle-bg-dark';
export const optionTileCheckboxClass = 'flex h-4 w-4 flex-shrink-0 items-center justify-center rounded-md border';
export const optionTileCheckboxActiveClass = 'border-arsm-accent bg-arsm-accent dark:border-arsm-accent-dark dark:bg-arsm-accent-dark';
export const optionTileCheckboxInactiveClass = 'border-arsm-border bg-transparent dark:border-arsm-border-dark';
export const hiddenCheckboxClass = 'pointer-events-none absolute opacity-0';

export const segmentedControlClass = 'grid min-w-0 grid-cols-2 gap-1.5 rounded-xl bg-arsm-toggle-bg p-1.5 dark:bg-arsm-toggle-bg-dark';

const segmentedControlOptionBaseClass = 'inline-flex min-h-11 min-w-0 items-center justify-center rounded-xl px-3 py-2 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/40 disabled:cursor-not-allowed disabled:opacity-60';
const segmentedControlOptionActiveClass = 'border border-arsm-accent/80 bg-arsm-accent text-arsm-on-accent ring-1 ring-arsm-accent-deep/20 dark:border-arsm-accent-dark/85 dark:bg-arsm-accent-dark dark:text-arsm-on-accent-dark dark:ring-arsm-accent-dark/35';
const segmentedControlOptionInactiveClass = 'bg-transparent text-arsm-label hover:bg-arsm-accent-subtle dark:text-arsm-label-dark dark:hover:bg-arsm-hover-dark';

export const getSegmentedControlOptionClass = (isActive: boolean): string =>
	`${segmentedControlOptionBaseClass} ${isActive ? segmentedControlOptionActiveClass : segmentedControlOptionInactiveClass}`;

export const schedulerMiniPrimaryActionButtonClass = `group pointer-events-auto inline-flex min-h-11 max-w-full min-w-0 items-center justify-center gap-1.5 rounded-full border border-arsm-accent/45 bg-arsm-accent-wash px-3 py-1.5 text-xs font-semibold text-arsm-primary hover:border-arsm-accent hover:bg-arsm-accent-subtle focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/45 disabled:cursor-not-allowed disabled:translate-y-0 disabled:opacity-60 dark:border-arsm-accent-dark/45 dark:bg-arsm-hover-dark dark:text-arsm-primary-dark dark:hover:border-arsm-accent-dark dark:hover:bg-arsm-toggle-bg-dark ${buttonMicroInteractionClass}`;
export const schedulerMiniNeutralActionButtonClass = `inline-flex min-h-11 min-w-0 max-w-full items-center justify-center gap-1.5 rounded-full border border-arsm-border bg-arsm-card px-3 py-1.5 text-xs font-semibold text-arsm-label hover:bg-arsm-toggle-bg max-[350px]:basis-full dark:border-arsm-border-dark dark:bg-arsm-input-dark dark:text-arsm-label-dark dark:hover:bg-arsm-toggle-bg-dark ${buttonMicroInteractionClass}`;
export const schedulerInlineClaimButtonClass = `group inline-flex h-11 min-h-11 w-auto min-w-0 max-w-full shrink-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-xl border border-arsm-accent/55 bg-arsm-accent-wash px-3 py-2 text-xs font-semibold leading-none text-arsm-primary hover:bg-arsm-accent-subtle focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/40 disabled:cursor-not-allowed disabled:opacity-50 dark:border-arsm-accent-dark/55 dark:bg-arsm-accent-dark/20 dark:text-arsm-primary-dark dark:hover:bg-arsm-accent-dark/30 ${buttonMicroInteractionClass}`;
export const schedulerInlineUnassignButtonClass = `group inline-flex h-11 min-h-11 w-auto min-w-0 max-w-full shrink-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-xl border border-arsm-error-border/70 bg-arsm-error-bg px-3 py-2 text-xs font-semibold leading-none text-arsm-error-text hover:bg-arsm-error-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/40 disabled:cursor-not-allowed disabled:opacity-50 dark:border-arsm-error-dark/70 dark:bg-arsm-error-bg-dark/60 dark:text-arsm-error-text-light dark:hover:bg-arsm-error-bg-dark/80 ${buttonMicroInteractionClass}`;

export const compactActionButtonBaseClass = `inline-flex min-h-11 min-w-0 max-w-full items-center justify-center gap-1 rounded-xl px-2.5 py-1.5 text-xs font-medium max-[350px]:w-full ${buttonMicroInteractionClass}`;
export const compactActionButtonNeutralClass = `${compactActionButtonBaseClass} border border-arsm-border text-arsm-label hover:bg-arsm-toggle-bg dark:border-arsm-border-dark dark:text-arsm-label-dark dark:hover:bg-arsm-toggle-bg-dark`;
export const compactSortToggleButtonClass = `inline-flex h-11 min-h-11 w-auto min-w-0 shrink-0 items-center justify-center gap-1 rounded-full border border-arsm-border bg-arsm-card px-3 py-2 text-[11px] font-semibold leading-none text-arsm-label whitespace-nowrap hover:bg-arsm-accent-wash dark:border-arsm-border-dark dark:bg-arsm-input-dark dark:text-arsm-label-dark dark:hover:bg-arsm-hover-dark/80 ${buttonMicroInteractionClass}`;
export const schedulerFilterControlBaseClass = 'inline-flex h-11 min-h-11 w-auto min-w-0 shrink-0 items-center justify-center gap-1.5 rounded-full border border-arsm-border bg-arsm-card px-3 py-2 text-xs font-semibold leading-none text-arsm-label transition-colors dark:border-arsm-border-dark dark:bg-arsm-input-dark dark:text-arsm-label-dark';
export const schedulerFilterChipButtonClass = `${schedulerFilterControlBaseClass} whitespace-nowrap hover:bg-arsm-accent-wash dark:hover:bg-arsm-hover-dark/80 ${buttonMicroInteractionClass}`;

const referenceChipActionBaseClass = `inline-flex h-11 min-h-11 min-w-0 max-w-full shrink-0 items-center justify-center gap-1.5 rounded-full border px-3.5 py-2 text-xs font-semibold leading-tight whitespace-nowrap ring-1 ring-transparent disabled:cursor-not-allowed disabled:opacity-60 max-[350px]:w-full ${buttonMicroInteractionClass}`;

export const referenceChipNeutralButtonClass = `${referenceChipActionBaseClass} border-arsm-border bg-arsm-toggle-bg text-arsm-label hover:border-arsm-accent/45 hover:bg-arsm-accent-wash dark:border-arsm-border-dark dark:bg-arsm-toggle-bg-dark dark:text-arsm-label-dark dark:hover:border-arsm-accent-dark/45 dark:hover:bg-arsm-hover-dark/90`;
export const referenceChipPrimaryButtonClass = `${referenceChipActionBaseClass} border-arsm-accent/60 bg-arsm-accent-subtle text-arsm-primary hover:border-arsm-accent hover:bg-arsm-accent-wash dark:border-arsm-accent-dark/60 dark:bg-arsm-accent-dark/25 dark:text-arsm-primary-dark dark:hover:border-arsm-accent-dark dark:hover:bg-arsm-accent-dark/35`;
export const referenceChipDangerButtonClass = `${referenceChipActionBaseClass} border-arsm-error-border/75 bg-arsm-error-bg text-arsm-error-text hover:border-arsm-error-text/40 hover:bg-arsm-error-soft dark:border-arsm-error-dark/75 dark:bg-arsm-error-bg-dark dark:text-arsm-error-text-light dark:hover:border-arsm-error-text-light/35 dark:hover:bg-arsm-error-bg-dark/85`;

const customersToolbarActionBaseClass = `inline-flex h-11 min-h-11 min-w-0 max-w-full shrink-0 items-center justify-center gap-1.5 rounded-2xl px-4 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-60 max-[350px]:w-full ${buttonMicroInteractionClass}`;

export const customersToolbarNeutralButtonClass = `${customersToolbarActionBaseClass} border border-arsm-border bg-arsm-toggle-bg font-medium text-arsm-label hover:bg-arsm-accent-subtle dark:border-arsm-border-dark dark:bg-arsm-toggle-bg-dark dark:text-arsm-label-dark dark:hover:bg-arsm-hover-dark`;
export const customersToolbarPrimaryButtonClass = `${customersToolbarActionBaseClass} bg-arsm-accent font-semibold text-arsm-on-accent hover:bg-arsm-accent-hover dark:bg-arsm-accent-dark dark:text-arsm-on-accent-dark dark:hover:bg-arsm-accent-dark-hover`;
export const customersToolbarDangerButtonClass = `${customersToolbarActionBaseClass} border border-arsm-error-border bg-arsm-error-bg font-semibold text-arsm-error-text hover:bg-arsm-error-soft dark:border-arsm-error-dark dark:bg-arsm-error-bg-dark dark:text-arsm-error-text-light dark:hover:bg-arsm-error-bg-dark/80`;

export const compactActionButtonAccentClass = `${compactActionButtonBaseClass} border border-arsm-accent/45 bg-arsm-accent-subtle font-semibold text-arsm-primary hover:bg-arsm-accent-wash dark:border-arsm-accent-dark/45 dark:bg-arsm-hover-dark dark:text-arsm-primary-dark dark:hover:bg-arsm-toggle-bg-dark`;
export const compactActionButtonDangerClass = `${compactActionButtonBaseClass} border border-arsm-error-border bg-arsm-error-bg text-arsm-error-text hover:bg-arsm-error-soft dark:border-arsm-error-dark dark:bg-arsm-error-bg-dark dark:text-arsm-error-text-light dark:hover:bg-arsm-error-bg-dark/80`;
export const schedulerMiniDangerActionButtonClass = `group pointer-events-auto inline-flex min-h-11 w-auto shrink-0 items-center gap-1 rounded-xl border border-arsm-error-border/70 bg-arsm-error-bg px-2.5 py-1.5 text-xs font-semibold text-arsm-error-text hover:bg-arsm-error-soft focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/45 disabled:cursor-not-allowed disabled:opacity-50 max-[350px]:w-full max-[350px]:justify-center dark:border-arsm-error-dark/70 dark:bg-arsm-error-bg-dark dark:text-arsm-error-text-light dark:hover:bg-arsm-error-bg-dark/80 ${buttonMicroInteractionClass}`;
export const schedulerMiniDangerStrongActionButtonClass = `group pointer-events-auto inline-flex min-h-11 max-w-full min-w-0 items-center justify-center gap-1.5 rounded-full border border-arsm-error-border/70 bg-arsm-error-bg px-3 py-1.5 text-xs font-semibold text-arsm-error-text hover:bg-arsm-error-softest focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-arsm-focus-ring/45 disabled:cursor-not-allowed disabled:translate-y-0 disabled:opacity-60 dark:border-arsm-error-dark/70 dark:bg-arsm-error-bg-dark dark:text-arsm-error-text-light dark:hover:bg-arsm-error-bg-dark/80 ${buttonMicroInteractionClass}`;

const togglePillBaseClass = `inline-flex h-11 min-h-11 min-w-11 max-w-full items-center justify-center rounded-xl border px-3.5 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50 max-[350px]:w-full ${buttonMicroInteractionClass}`;
const togglePillActiveClass = 'border-arsm-accent/80 bg-arsm-accent text-arsm-on-accent ring-1 ring-arsm-accent-deep/20 dark:border-arsm-accent-dark/85 dark:bg-arsm-accent-dark dark:text-arsm-on-accent-dark dark:ring-arsm-accent-dark/35';
const togglePillInactiveClass = 'border-arsm-border bg-arsm-toggle-bg text-arsm-label hover:border-arsm-accent/50 hover:bg-arsm-accent-subtle dark:border-arsm-border-dark dark:bg-arsm-toggle-bg-dark dark:text-arsm-label-dark dark:hover:border-arsm-accent-dark/50 dark:hover:bg-arsm-hover-dark';

export const getTogglePillClass = (isActive: boolean): string =>
	`${togglePillBaseClass} ${isActive ? togglePillActiveClass : togglePillInactiveClass}`;

export const buttonClass = customersToolbarPrimaryButtonClass;
export const secondaryButtonClass = customersToolbarNeutralButtonClass;
export const dangerButtonClass = customersToolbarDangerButtonClass;